spring:
  application:
    name: znjf-activity-provider
  profiles:
    active: '@profileActive@'

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/*.xml
  typeAliasesPackage: com.znjf33