spring:
  # DataSource Config
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/maweijun?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: root
      password: 000000
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    password: 000000 #密码
    port: 6379
    timeout: 0
    pool:
      max-active: 8 #最大连接数
      max-idle: 8 #最大空闲连接数
      max-wait: -1 #最大等待时间
      min-idle: 0
  # DataSource Config
  dubbo:
    container: logback,spring
    shutdown:
      hook: true
    application:
      name: springboot-demo-service
      owner: springboot-demo
      logger: slf4j
    registry:
      protocol: zookeeper
      address: 127.0.0.1:2181
      client: curator
      file: tmp/springboot-demo-service.cache
    provider:
      timeout: 80000
      retries: 0
      actives: 100
      loadbalance: leastactive
      weight: 300
    protocol:
      name: dubbo
      port: 20880
      threads: 500
    logback:
      level: info
    monitor:
      protocol: registry

server:
  port: 8080